services:
  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_part2:/data/db

  backend2:
    image: node:18
    container_name: mern-backend2
    working_dir: /app
    volumes:
      - ./Backend:/app
    command: bash -c "npm install && npm start"
    environment:
      - MONGO_URI=mongodb://mongo2:27017/mern_db
    depends_on:
      - mongo2
    ports:
      - "5001:5000"

  frontend2:
    image: node:18
    container_name: mern-frontend2
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:5173"
    depends_on:
      - backend2

  test-runner:
    image: markhobson/maven-chrome:latest
    depends_on:
      - frontend2
    working_dir: /usr/src/app
    volumes:
      - ./tests:/usr/src/app
    environment:
      BASE_URL: http://frontend2:3001
    shm_size: "2gb"
    command: mvn test

volumes:
  mongo_data_part2:
